org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Allow building from paths with non-ASCII characters on Windows.
# This bypasses the Gradle path check warning described here:
# https://issuetracker.google.com/issues/37014942
android.overridePathCheck=true
